# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
    
    - run: |
        docker build -t ghcr.io/demoserievideo/sample-artifact-docker/sample:latest -f Dockerfile .
        docker tag ghcr.io/demoserievideo/sample-artifact-docker/sample:latest ghcr.io/demoserievideo/sample-artifact-docker/sample:${{ github.sha }}
    
    - run: |
        docker push ghcr.io/demoserievideo/sample-artifact-docker/sample:latest
        docker push ghcr.io/demoserievideo/sample-artifact-docker/sample:${{ github.sha }}
